# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36484f3dff08090e4eb84d0ee443de53821df1ecdffaf7691f7a0f23d9d2fd64e29f3174bbf23eb9cbf8d99baa6cb02146871ce1e71cff628df8ba35e1b63f88

test:
  secret_key_base: 7c6d673c1dbdac258c54a8155bb3a19ff2bb545d8e801ecdce6da2e58ded642e4199f71c43a4819f12b06be042f78cbf7392d425f54fbfcc9f99b70d3ca5424d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
